/**
 * @file shared/tiptap-email.ts
 * @description The draft studio's Tiptap → email-HTML serialiser, DOM-free and
 * dependency-light: the document types, the HTML pre-clean the browser editor
 * is seeded with, and the reduction + serialisation of a Tiptap document to
 * clean, email-ready HTML.
 *
 * Why this is hand-written rather than `@tiptap/html`'s `generateHTML`:
 * `generateHTML` cannot run in a Cloudflare Worker. Measured 2026-10-04 with
 * `wrangler dev --local`: `@tiptap/html/server` builds a `happy-dom` `Window`,
 * which calls Node's `vm.runInContext`, and workerd has no `vm` →
 * `TypeError: The "contextifiedObject" argument must be a vm.Context`. Feeding
 * the ProseMirror `DOMSerializer` a `zeed-dom` document instead runs in workerd
 * but mis-escapes inline marks (`<strong>` arrives as text). The draft studio
 * runs `tiptapToHtml` on the Worker (to normalise a saved edit before it is
 * sent), so it needs a serialiser that works there. Since `gmail/compose.ts`
 * owns the wire format and the editor is only an input surface, the body only
 * ever needs the small, fixed node/mark set below — a direct, deterministic
 * string serialiser is both sufficient and workerd-safe (this is exactly what
 * the PlateJS-era `plate-html.ts#plateToHtml` was). Tiptap's `generateJSON` is
 * still used for the inverse (parsing HTML back to a doc) in `tiptap-html.ts`,
 * which only runs in Node tests.
 *
 * The frontend imports only from THIS file — the live Tiptap editor parses its
 * own HTML in the browser, so it needs the pre-clean, the serialiser and the
 * types, none of which touch `happy-dom`.
 */
import { parse } from "node-html-parser";

/** A Tiptap / ProseMirror JSON node, loose enough for the editor's `getJSON()`. */
export interface TiptapNode {
  type?: string;
  text?: string;
  marks?: { type: string; attrs?: Record<string, unknown> }[];
  attrs?: Record<string, unknown>;
  content?: TiptapNode[];
}

/** The top-level Tiptap document the editor produces and consumes. */
export interface TiptapDoc {
  type: "doc";
  content?: TiptapNode[];
}

/**
 * Drop the hidden machine markers (`data-plaintext="omit"` — the reference id
 * and authorship watermark) plus any `<style>`/`<script>`, so the body can be
 * handed to the browser editor as its initial HTML content without those
 * becoming editable text. They are regenerated by `gmail/compose.ts` on send.
 */
export function stripHiddenMarkers(html: string): string {
  const root = parse(html ?? "", { comment: false });
  root.querySelectorAll('[data-plaintext="omit"]').forEach((n) => n.remove());
  root.querySelectorAll("style,script").forEach((n) => n.remove());
  return root.toString();
}

/* ---------------------------------------------------- email-safe reduction - */

/** Block node types the email body may carry, as-is. */
const ALLOWED_BLOCKS = new Set([
  "paragraph",
  "heading",
  "blockquote",
  "codeBlock",
  "bulletList",
  "orderedList",
  "listItem",
  "horizontalRule",
  "hardBreak",
  "text",
]);

/** Marks an email body may carry; everything else (highlight, textStyle…) is dropped. */
const ALLOWED_MARKS = new Set(["bold", "italic", "underline", "strike", "code", "link"]);

/** Block attributes worth keeping per node type; all others (textAlign…) are dropped. */
const KEPT_ATTRS: Record<string, Set<string>> = {
  heading: new Set(["level"]),
  orderedList: new Set(["start"]),
  codeBlock: new Set(["language"]),
};

function pickAttrs(type: string, attrs?: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!attrs) return undefined;
  const keep = KEPT_ATTRS[type];
  if (!keep) return undefined;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(attrs)) if (keep.has(k) && v != null) out[k] = v;
  return Object.keys(out).length ? out : undefined;
}

function cleanMarks(marks?: TiptapNode["marks"]): TiptapNode["marks"] | undefined {
  if (!marks?.length) return undefined;
  const out = marks
    .filter((m) => ALLOWED_MARKS.has(m.type))
    .map((m) => (m.type === "link" ? { type: "link", attrs: { href: m.attrs?.href ?? "" } } : { type: m.type }));
  return out.length ? out : undefined;
}

/**
 * Recursively reduce an editor node to the email-safe subset. Task lists become
 * plain bullet lists, task items plain list items (the checkbox is not email),
 * disallowed marks and layout attributes are dropped, and any node type that is
 * neither allowed nor remappable collapses to a paragraph so its text survives.
 */
function cleanNode(node: TiptapNode): TiptapNode {
  if (node.type === "text" || node.text != null) {
    const out: TiptapNode = { type: "text", text: node.text ?? "" };
    const marks = cleanMarks(node.marks);
    if (marks) out.marks = marks;
    return out;
  }

  let type = node.type ?? "paragraph";
  if (type === "taskList") type = "bulletList";
  else if (type === "taskItem") type = "listItem";
  else if (!ALLOWED_BLOCKS.has(type)) type = "paragraph";

  const content = node.content?.map(cleanNode);
  const out: TiptapNode = { type };
  const attrs = pickAttrs(type, node.attrs);
  if (attrs) out.attrs = attrs;
  if (content?.length) out.content = content;
  return out;
}

/** Reduce a whole document to the email-safe subset. */
export function toEmailDoc(doc: TiptapDoc): TiptapDoc {
  return { type: "doc", content: (doc.content ?? []).map(cleanNode) };
}

/** A paragraph with no text once hard breaks and whitespace are ignored. */
export function isBlankParagraph(node: TiptapNode): boolean {
  const text = (node.content ?? [])
    .filter((c) => c.type === "text")
    .map((c) => c.text ?? "")
    .join("")
    .trim();
  return text.length === 0;
}

/* --------------------------------------------------------------- HTML out -- */

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** Block node type → HTML tag (single-tag blocks). */
const BLOCK_TAG: Record<string, string> = {
  paragraph: "p",
  blockquote: "blockquote",
  bulletList: "ul",
  orderedList: "ol",
};

/**
 * Wrap a text node's content in its marks. The nesting order is fixed so the
 * output is deterministic (the studio's "edit twice, no drift" guarantee):
 * link outermost, then bold, italic, underline, strike, with code innermost.
 */
function textToHtml(node: TiptapNode): string {
  let html = escapeHtml(node.text ?? "");
  if (!html && !(node.marks ?? []).length) return html;
  const has = (type: string) => (node.marks ?? []).some((m) => m.type === type);
  if (has("code")) html = `<code>${html}</code>`;
  if (has("strike")) html = `<s>${html}</s>`;
  if (has("underline")) html = `<u>${html}</u>`;
  if (has("italic")) html = `<em>${html}</em>`;
  if (has("bold")) html = `<strong>${html}</strong>`;
  const link = (node.marks ?? []).find((m) => m.type === "link");
  if (link) html = `<a href="${escapeHtml(String(link.attrs?.href ?? ""))}">${html}</a>`;
  return html;
}

/** Concatenate the serialised inline children of a block. */
function inlineChildren(nodes: TiptapNode[] | undefined): string {
  let out = "";
  for (const child of nodes ?? []) {
    if (child.type === "hardBreak") out += "<br>";
    else if (child.type === "text" || child.text != null) out += textToHtml(child);
  }
  return out;
}

/**
 * A list item is `paragraph (list)?`. The leading paragraph is INLINED (no `<p>`
 * wrapper) so items read as `<li>text</li>`, and any nested list follows.
 */
function listItemToHtml(node: TiptapNode): string {
  let out = "";
  let paragraphSeen = false;
  for (const child of node.content ?? []) {
    if (!paragraphSeen && child.type === "paragraph") {
      out += inlineChildren(child.content);
      paragraphSeen = true;
    } else {
      out += blockToHtml(child);
    }
  }
  return `<li>${out}</li>`;
}

/** One email-safe block node → HTML. */
function blockToHtml(node: TiptapNode): string {
  switch (node.type) {
    case "heading": {
      const level = Math.min(3, Math.max(1, Number(node.attrs?.level) || 1));
      return `<h${level}>${inlineChildren(node.content)}</h${level}>`;
    }
    case "codeBlock":
      return `<pre><code>${escapeHtml(plainTextOf(node))}</code></pre>`;
    case "listItem":
      return listItemToHtml(node);
    case "horizontalRule":
      return "<hr>";
    case "bulletList":
    case "orderedList":
    case "blockquote":
      return `<${BLOCK_TAG[node.type]}>${(node.content ?? []).map(blockToHtml).join("")}</${BLOCK_TAG[node.type]}>`;
    case "paragraph":
    default: {
      const inner = inlineChildren(node.content);
      return inner ? `<p>${inner}</p>` : "<p></p>";
    }
  }
}

/** All text under a node, marks ignored (used for code blocks). */
function plainTextOf(node: TiptapNode): string {
  if (node.type === "text" || node.text != null) return node.text ?? "";
  return (node.content ?? []).map(plainTextOf).join("");
}

/**
 * Serialise an already-email-safe document (the output of `toEmailDoc`) to clean
 * semantic HTML — plain `<p>/<strong>/<ul>/<a>`… with no class, style or data-*
 * attribute. Deterministic string building, so it runs anywhere the Worker does.
 */
export function serializeEmailDoc(doc: TiptapDoc): string {
  return (doc.content ?? []).map(blockToHtml).join("");
}

/** Tiptap doc → clean semantic HTML, ready for `gmail/compose.ts` to restyle. */
export function tiptapToHtml(doc: TiptapDoc): string {
  const clean = toEmailDoc(doc);
  if (!clean.content?.length) return "";
  return serializeEmailDoc(clean);
}
