/**
 * @file src/backend/pdf/templates/builtin.ts
 * @description Built-in, production-grade PDF templates for pdfme.
 * Ready for immediate rendering or user customization.
 */
import { defaultTableSchema } from "../plugins";
import type { PdfmeTemplateDefinition } from "../types";

export interface BuiltinTemplate {
  id: string;
  name: string;
  description: string;
  category: "invoice" | "certificate" | "report" | "receipt" | "contract" | "shipping" | "ticket";
  thumbnailUrl?: string;
  schema: PdfmeTemplateDefinition;
  sampleData: Record<string, any>[];
}

const standardA4BasePdf = {
  width: 210,
  height: 297,
  padding: [10, 10, 10, 10] as [number, number, number, number],
};

export const BUILTIN_TEMPLATES: BuiltinTemplate[] = [
  // 1. Modern Business Invoice
  {
    id: "tmpl_invoice_modern",
    name: "Modern Business Invoice",
    description: "Professional corporate invoice with header banner, client info, itemized table, total summary, and payment QR code.",
    category: "invoice",
    schema: {
      basePdf: standardA4BasePdf,
      schemas: [
        [
          {
            name: "headerBanner",
            type: "rectangle",
            position: { x: 10, y: 10 },
            width: 190,
            height: 24,
            color: "#090d16",
          },
          {
            name: "companyTitle",
            type: "text",
            position: { x: 16, y: 15 },
            width: 90,
            height: 10,
            fontSize: 16,
            fontColor: "#ffffff",
          },
          {
            name: "invoiceNumber",
            type: "text",
            position: { x: 110, y: 16 },
            width: 84,
            height: 8,
            fontSize: 12,
            fontColor: "#38bdf8",
            alignment: "right",
          },
          // Issuer & Client info
          {
            name: "billedToLabel",
            type: "text",
            position: { x: 12, y: 40 },
            width: 80,
            height: 6,
            fontSize: 9,
            fontColor: "#94a3b8",
          },
          {
            name: "clientName",
            type: "text",
            position: { x: 12, y: 47 },
            width: 80,
            height: 7,
            fontSize: 12,
            fontColor: "#0f172a",
          },
          {
            name: "clientDetails",
            type: "text",
            position: { x: 12, y: 55 },
            width: 80,
            height: 14,
            fontSize: 9,
            fontColor: "#475569",
            lineHeight: 1.3,
          },
          {
            name: "invoiceDateLabel",
            type: "text",
            position: { x: 120, y: 40 },
            width: 74,
            height: 6,
            fontSize: 9,
            fontColor: "#94a3b8",
            alignment: "right",
          },
          {
            name: "invoiceDate",
            type: "text",
            position: { x: 120, y: 47 },
            width: 74,
            height: 7,
            fontSize: 11,
            fontColor: "#0f172a",
            alignment: "right",
          },
          {
            name: "dueDate",
            type: "text",
            position: { x: 120, y: 55 },
            width: 74,
            height: 6,
            fontSize: 9,
            fontColor: "#64748b",
            alignment: "right",
          },
          // Line items table
          {
            ...defaultTableSchema,
            name: "lineItems",
            position: { x: 10, y: 76 },
            width: 190,
            height: 70,
            showHead: true,
            head: ["Description", "Quantity", "Rate", "Amount"],
            headWidthPercentages: [50, 15, 15, 20],
            tableStyles: { borderColor: "#e2e8f0", borderWidth: 0.3 },
            headStyles: {
              ...defaultTableSchema.headStyles,
              fontColor: "#ffffff",
              backgroundColor: "#0f172a",
              fontSize: 10,
            },
            bodyStyles: {
              ...defaultTableSchema.bodyStyles,
              fontSize: 9,
              fontColor: "#1e293b",
              alternateBackgroundColor: "#f8fafc",
            },
          },
          // Summary & Totals
          {
            name: "notes",
            type: "text",
            position: { x: 12, y: 160 },
            width: 100,
            height: 25,
            fontSize: 9,
            fontColor: "#64748b",
            lineHeight: 1.3,
          },
          {
            name: "totalLabel",
            type: "text",
            position: { x: 120, y: 160 },
            width: 35,
            height: 7,
            fontSize: 11,
            fontColor: "#64748b",
            alignment: "right",
          },
          {
            name: "totalAmount",
            type: "text",
            position: { x: 155, y: 158 },
            width: 40,
            height: 10,
            fontSize: 16,
            fontColor: "#0f172a",
            alignment: "right",
          },
          // Payment QR Code
          {
            name: "paymentQr",
            type: "qrcode",
            position: { x: 12, y: 200 },
            width: 25,
            height: 25,
          },
          {
            name: "qrInstruction",
            type: "text",
            position: { x: 42, y: 205 },
            width: 80,
            height: 15,
            fontSize: 9,
            fontColor: "#64748b",
            lineHeight: 1.2,
          },
        ],
      ],
    },
    sampleData: [
      {
        companyTitle: "ACME CLOUD SOLUTIONS",
        invoiceNumber: "INV-2026-0891",
        billedToLabel: "BILLED TO",
        clientName: "Starlight Digital Corp",
        clientDetails: "742 Evergreen Way, Suite 400\nSan Francisco, CA 94107\nattn: Accounts Payable",
        invoiceDateLabel: "INVOICE DATE & TERMS",
        invoiceDate: "September 28, 2026",
        dueDate: "Due upon receipt (Net 15)",
        lineItems: JSON.stringify([
          ["Cloudflare Workers Architecture & Edge Security", "32 hrs", "$220.00", "$7,040.00"],
          ["Google Workspace DWD Multi-Account Gateway", "1 sys", "$3,500.00", "$3,500.00"],
          ["Automated PDF & Storage Synthesis Pipeline", "1 mod", "$2,400.00", "$2,400.00"],
          ["High-Availability Edge Cache Configuration", "8 hrs", "$180.00", "$1,440.00"],
        ]),
        notes: "Thank you for your business. Remit electronic ACH transfer to Silicon Valley Bank routing #121000358, acct #98421039.",
        totalLabel: "TOTAL DUE:",
        totalAmount: "$14,380.00",
        paymentQr: "https://google-workspace-mcp.hacolby.workers.dev/pay/INV-2026-0891",
        qrInstruction: "Scan with your mobile camera or banking app to open instant electronic checkout.",
      },
    ],
  },

  // 2. Certificate of Completion & Achievement
  {
    id: "tmpl_certificate_achievement",
    name: "Certificate of Achievement",
    description: "Elegant certificate of completion with ornamental borders, recipient name, honors description, and validation seal.",
    category: "certificate",
    schema: {
      basePdf: { width: 297, height: 210, padding: [15, 15, 15, 15] }, // Landscape A4
      schemas: [
        [
          {
            name: "outerBorder",
            type: "rectangle",
            position: { x: 10, y: 10 },
            width: 277,
            height: 190,
            color: "#f8fafc",
          },
          {
            name: "innerBorder",
            type: "rectangle",
            position: { x: 14, y: 14 },
            width: 269,
            height: 182,
            color: "#ffffff",
          },
          {
            name: "headerPill",
            type: "rectangle",
            position: { x: 100, y: 22 },
            width: 97,
            height: 6,
            color: "#d97706",
          },
          {
            name: "certTitle",
            type: "text",
            position: { x: 20, y: 35 },
            width: 257,
            height: 12,
            fontSize: 22,
            fontColor: "#0f172a",
            alignment: "center",
          },
          {
            name: "certSubtitle",
            type: "text",
            position: { x: 20, y: 50 },
            width: 257,
            height: 8,
            fontSize: 11,
            fontColor: "#64748b",
            alignment: "center",
          },
          {
            name: "presentedTo",
            type: "text",
            position: { x: 20, y: 68 },
            width: 257,
            height: 6,
            fontSize: 9,
            fontColor: "#94a3b8",
            alignment: "center",
          },
          {
            name: "recipientName",
            type: "text",
            position: { x: 20, y: 77 },
            width: 257,
            height: 14,
            fontSize: 24,
            fontColor: "#0284c7",
            alignment: "center",
          },
          {
            name: "certDescription",
            type: "text",
            position: { x: 40, y: 98 },
            width: 217,
            height: 22,
            fontSize: 11,
            fontColor: "#334155",
            alignment: "center",
            lineHeight: 1.4,
          },
          {
            name: "dateIssued",
            type: "text",
            position: { x: 35, y: 150 },
            width: 70,
            height: 8,
            fontSize: 10,
            fontColor: "#475569",
            alignment: "center",
          },
          {
            name: "issuerSignature",
            type: "text",
            position: { x: 190, y: 150 },
            width: 70,
            height: 8,
            fontSize: 10,
            fontColor: "#475569",
            alignment: "center",
          },
          {
            name: "verifyQr",
            type: "qrcode",
            position: { x: 138, y: 142 },
            width: 22,
            height: 22,
          },
        ],
      ],
    },
    sampleData: [
      {
        certTitle: "CERTIFICATE OF EXCELLENCE",
        certSubtitle: "FOR OUTSTANDING ENGINEERING CONTRIBUTIONS",
        presentedTo: "THIS CERTIFICATE IS PROUDLY CONFERRED UPON",
        recipientName: "Alex Rivera",
        certDescription: "In recognition of distinguished leadership, exceptional technical craftsmanship, and architectural innovation in deploying multi-tenant Cloudflare edge services and Google Workspace automation.",
        dateIssued: "Date: September 28, 2026",
        issuerSignature: "Dr. Evelyn Vance\nChief Technology Officer",
        verifyQr: "https://google-workspace-mcp.hacolby.workers.dev/cert/verify/94821",
      },
    ],
  },

  // 3. Executive Brief & KPI Report
  {
    id: "tmpl_executive_report",
    name: "Executive Brief & KPI Report",
    description: "Compact executive summary with metric highlight cards, status narrative, and milestone breakdown table.",
    category: "report",
    schema: {
      basePdf: standardA4BasePdf,
      schemas: [
        [
          {
            name: "topBar",
            type: "rectangle",
            position: { x: 10, y: 10 },
            width: 190,
            height: 18,
            color: "#1e1b4b",
          },
          {
            name: "reportTitle",
            type: "text",
            position: { x: 15, y: 14 },
            width: 120,
            height: 8,
            fontSize: 14,
            fontColor: "#ffffff",
          },
          {
            name: "reportPeriod",
            type: "text",
            position: { x: 135, y: 15 },
            width: 60,
            height: 6,
            fontSize: 9,
            fontColor: "#c7d2fe",
            alignment: "right",
          },
          // Metric Cards
          {
            name: "card1Bg",
            type: "rectangle",
            position: { x: 10, y: 34 },
            width: 60,
            height: 24,
            color: "#f1f5f9",
          },
          {
            name: "kpi1Label",
            type: "text",
            position: { x: 14, y: 38 },
            width: 52,
            height: 5,
            fontSize: 8,
            fontColor: "#64748b",
          },
          {
            name: "kpi1Value",
            type: "text",
            position: { x: 14, y: 44 },
            width: 52,
            height: 9,
            fontSize: 15,
            fontColor: "#0f172a",
          },
          {
            name: "card2Bg",
            type: "rectangle",
            position: { x: 75, y: 34 },
            width: 60,
            height: 24,
            color: "#f1f5f9",
          },
          {
            name: "kpi2Label",
            type: "text",
            position: { x: 79, y: 38 },
            width: 52,
            height: 5,
            fontSize: 8,
            fontColor: "#64748b",
          },
          {
            name: "kpi2Value",
            type: "text",
            position: { x: 79, y: 44 },
            width: 52,
            height: 9,
            fontSize: 15,
            fontColor: "#0f172a",
          },
          {
            name: "card3Bg",
            type: "rectangle",
            position: { x: 140, y: 34 },
            width: 60,
            height: 24,
            color: "#f1f5f9",
          },
          {
            name: "kpi3Label",
            type: "text",
            position: { x: 144, y: 38 },
            width: 52,
            height: 5,
            fontSize: 8,
            fontColor: "#64748b",
          },
          {
            name: "kpi3Value",
            type: "text",
            position: { x: 144, y: 44 },
            width: 52,
            height: 9,
            fontSize: 15,
            fontColor: "#059669",
          },
          // Section Heading
          {
            name: "summaryHeading",
            type: "text",
            position: { x: 10, y: 65 },
            width: 190,
            height: 7,
            fontSize: 12,
            fontColor: "#0f172a",
          },
          {
            name: "summaryBody",
            type: "text",
            position: { x: 10, y: 74 },
            width: 190,
            height: 38,
            fontSize: 10,
            fontColor: "#334155",
            lineHeight: 1.4,
          },
          // Milestones Table
          {
            ...defaultTableSchema,
            name: "milestonesTable",
            position: { x: 10, y: 120 },
            width: 190,
            height: 60,
            showHead: true,
            head: ["Milestone", "Owner", "Target Date", "Status"],
            headWidthPercentages: [40, 20, 20, 20],
            tableStyles: { borderColor: "#cbd5e1", borderWidth: 0.3 },
            headStyles: {
              ...defaultTableSchema.headStyles,
              fontColor: "#ffffff",
              backgroundColor: "#1e1b4b",
              fontSize: 9,
            },
            bodyStyles: {
              ...defaultTableSchema.bodyStyles,
              fontSize: 8.5,
              alternateBackgroundColor: "#f8fafc",
            },
          },
        ],
      ],
    },
    sampleData: [
      {
        reportTitle: "Q3 INFRASTRUCTURE PERFORMANCE",
        reportPeriod: "Q3 2026 | Cloud Eng",
        kpi1Label: "GLOBAL AVAILABILITY",
        kpi1Value: "99.994%",
        kpi2Label: "EDGE P95 LATENCY",
        kpi2Value: "18.4 ms",
        kpi3Label: "COST REDUCTION",
        kpi3Value: "-31.2%",
        summaryHeading: "Executive Summary & Fleet Health",
        summaryBody: "During Q3, the infrastructure fleet successfully migrated key routing and template generation workloads to Cloudflare Workers assets and D1 database layers. Overall operational overhead dropped substantially while edge execution performance beat our SLA targets across all continental points of presence.",
        milestonesTable: JSON.stringify([
          ["Unified Google Workspace MCP Gateway", "Core Team", "Aug 15", "Completed"],
          ["High-Speed Edge PDF Synthesis Engine", "Justin B.", "Sep 28", "Active"],
          ["Multi-Region R2 Storage Synchronization", "Infra Lead", "Oct 12", "On Track"],
          ["Zero-Trust Document Sharing Hardening", "SecOps", "Oct 30", "Planning"],
        ]),
      },
    ],
  },

  // 4. Sales Receipt
  {
    id: "tmpl_sales_receipt",
    name: "Customer Sales Receipt",
    description: "Compact transactional receipt with itemized register breakdown, tax calculation, and retail barcode.",
    category: "receipt",
    schema: {
      basePdf: { width: 148, height: 210, padding: [8, 8, 8, 8] }, // A5
      schemas: [
        [
          {
            name: "merchantName",
            type: "text",
            position: { x: 8, y: 10 },
            width: 132,
            height: 8,
            fontSize: 14,
            fontColor: "#0f172a",
            alignment: "center",
          },
          {
            name: "merchantAddress",
            type: "text",
            position: { x: 8, y: 19 },
            width: 132,
            height: 10,
            fontSize: 8,
            fontColor: "#64748b",
            alignment: "center",
            lineHeight: 1.2,
          },
          {
            name: "receiptMeta",
            type: "text",
            position: { x: 8, y: 34 },
            width: 132,
            height: 12,
            fontSize: 8.5,
            fontColor: "#334155",
            lineHeight: 1.3,
          },
          {
            ...defaultTableSchema,
            name: "items",
            position: { x: 8, y: 50 },
            width: 132,
            height: 50,
            showHead: true,
            head: ["Item", "Qty", "Price", "Subtotal"],
            headWidthPercentages: [50, 14, 18, 18],
            tableStyles: { borderColor: "#cbd5e1", borderWidth: 0.2 },
            headStyles: {
              ...defaultTableSchema.headStyles,
              fontColor: "#0f172a",
              backgroundColor: "#f1f5f9",
              fontSize: 8,
            },
            bodyStyles: {
              ...defaultTableSchema.bodyStyles,
              fontSize: 7.5,
            },
          },
          {
            name: "totalsText",
            type: "text",
            position: { x: 50, y: 110 },
            width: 90,
            height: 20,
            fontSize: 9,
            fontColor: "#0f172a",
            alignment: "right",
            lineHeight: 1.4,
          },
          {
            name: "receiptBarcode",
            type: "code128",
            position: { x: 24, y: 140 },
            width: 100,
            height: 18,
          },
          {
            name: "thankYou",
            type: "text",
            position: { x: 8, y: 165 },
            width: 132,
            height: 8,
            fontSize: 8,
            fontColor: "#94a3b8",
            alignment: "center",
          },
        ],
      ],
    },
    sampleData: [
      {
        merchantName: "NEXUS HARDWARE & CLOUD LABS",
        merchantAddress: "126 Colby Street, San Francisco, CA 94134\nTel: (415) 555-0199 | support@nexuslabs.dev",
        receiptMeta: "Receipt #: REC-2026-9481\nDate: 2026-09-28 15:42 PST\nCashier: Terminal #4 (Justin B.)",
        items: JSON.stringify([
          ["Cat6A Bulk Cable 1000ft", "1", "$189.00", "$189.00"],
          ["SFP+ 10G Optical Transceiver", "4", "$42.50", "$170.00"],
          ["Keystone Jack Patch Panel 24-Port", "2", "$35.00", "$70.00"],
          ["Precision Cable Stripper & Crimper", "1", "$29.99", "$29.99"],
        ]),
        totalsText: "Subtotal: $458.99\nSales Tax (8.625%): $39.59\nTOTAL PAID: $498.58\nPayment: Apple Pay (Visa ...8812)",
        receiptBarcode: "REC202694818812",
        thankYou: "Retain receipt for returns within 30 days. Thank you for your visit!",
      },
    ],
  },

  // 5. Professional Services Agreement
  {
    id: "tmpl_service_agreement",
    name: "Professional Services Agreement",
    description: "Legal and consulting agreement with scope clauses, compensation schedules, and dual signature execution blocks.",
    category: "contract",
    schema: {
      basePdf: standardA4BasePdf,
      schemas: [
        [
          {
            name: "contractTitle",
            type: "text",
            position: { x: 10, y: 14 },
            width: 190,
            height: 10,
            fontSize: 16,
            fontColor: "#0f172a",
            alignment: "center",
          },
          {
            name: "effectiveDateNotice",
            type: "text",
            position: { x: 10, y: 26 },
            width: 190,
            height: 6,
            fontSize: 9,
            fontColor: "#64748b",
            alignment: "center",
          },
          {
            name: "partiesIntro",
            type: "text",
            position: { x: 12, y: 38 },
            width: 186,
            height: 20,
            fontSize: 9.5,
            fontColor: "#1e293b",
            lineHeight: 1.4,
          },
          {
            name: "clause1Heading",
            type: "text",
            position: { x: 12, y: 62 },
            width: 186,
            height: 6,
            fontSize: 10,
            fontColor: "#0f172a",
          },
          {
            name: "clause1Body",
            type: "text",
            position: { x: 12, y: 70 },
            width: 186,
            height: 35,
            fontSize: 9,
            fontColor: "#334155",
            lineHeight: 1.4,
          },
          {
            name: "clause2Heading",
            type: "text",
            position: { x: 12, y: 110 },
            width: 186,
            height: 6,
            fontSize: 10,
            fontColor: "#0f172a",
          },
          {
            name: "clause2Body",
            type: "text",
            position: { x: 12, y: 118 },
            width: 186,
            height: 35,
            fontSize: 9,
            fontColor: "#334155",
            lineHeight: 1.4,
          },
          // Signatures
          {
            name: "sigLine1",
            type: "line",
            position: { x: 12, y: 200 },
            width: 75,
            height: 1,
            color: "#64748b",
          },
          {
            name: "sigLabel1",
            type: "text",
            position: { x: 12, y: 203 },
            width: 75,
            height: 12,
            fontSize: 8.5,
            fontColor: "#475569",
            lineHeight: 1.3,
          },
          {
            name: "sigLine2",
            type: "line",
            position: { x: 120, y: 200 },
            width: 75,
            height: 1,
            color: "#64748b",
          },
          {
            name: "sigLabel2",
            type: "text",
            position: { x: 120, y: 203 },
            width: 75,
            height: 12,
            fontSize: 8.5,
            fontColor: "#475569",
            lineHeight: 1.3,
          },
        ],
      ],
    },
    sampleData: [
      {
        contractTitle: "MASTER SERVICES & ENGINEERING AGREEMENT",
        effectiveDateNotice: "Contract Ref: MSA-2026-ENG · Effective as of September 28, 2026",
        partiesIntro: "This Master Services Agreement ('Agreement') is entered into between Colby Technologies LLC ('Provider'), having its principal place of business in San Francisco, CA, and Acme Enterprise Systems ('Client').",
        clause1Heading: "1. Scope of Engagement & Deliverables",
        clause1Body: "Provider shall deliver high-performance Cloudflare Worker microservices, automated PDF synthesis pipelines, and Google Workspace Domain-Wide Delegation integrations in accordance with project task definitions and verified pull requests.",
        clause2Heading: "2. Confidentiality & Intellectual Property",
        clause2Body: "All custom codebase modifications and proprietary configurations developed under this scope shall vest in Client upon full disbursement of stated fees. Both parties agree to maintain strict confidentiality regarding authentication credentials and infrastructure architecture.",
        sigLabel1: "PROVIDER: Colby Technologies LLC\nBy: Justin Bishop, Principal Architect\nDate: September 28, 2026",
        sigLabel2: "CLIENT: Acme Enterprise Systems\nBy: Authorized Officer Signature\nDate: ________________________",
      },
    ],
  },

  // 6. Logistics Packing Slip & Shipping Manifest
  {
    id: "tmpl_shipping_manifest",
    name: "Shipping Manifest & Packing Slip",
    description: "Dispatch packing list with origin/destination shipping blocks, parcel inventory, and tracking barcode.",
    category: "shipping",
    schema: {
      basePdf: standardA4BasePdf,
      schemas: [
        [
          {
            name: "headerTitle",
            type: "text",
            position: { x: 10, y: 12 },
            width: 100,
            height: 8,
            fontSize: 16,
            fontColor: "#0f172a",
          },
          {
            name: "trackingBarcode",
            type: "code128",
            position: { x: 120, y: 10 },
            width: 80,
            height: 15,
          },
          {
            name: "trackingNumberText",
            type: "text",
            position: { x: 120, y: 27 },
            width: 80,
            height: 5,
            fontSize: 8,
            fontColor: "#64748b",
            alignment: "center",
          },
          // Ship from & Ship to
          {
            name: "fromBox",
            type: "rectangle",
            position: { x: 10, y: 38 },
            width: 90,
            height: 30,
            color: "#f8fafc",
          },
          {
            name: "fromLabel",
            type: "text",
            position: { x: 14, y: 41 },
            width: 80,
            height: 4,
            fontSize: 7.5,
            fontColor: "#94a3b8",
          },
          {
            name: "fromAddress",
            type: "text",
            position: { x: 14, y: 47 },
            width: 82,
            height: 18,
            fontSize: 8.5,
            fontColor: "#1e293b",
            lineHeight: 1.3,
          },
          {
            name: "toBox",
            type: "rectangle",
            position: { x: 110, y: 38 },
            width: 90,
            height: 30,
            color: "#f8fafc",
          },
          {
            name: "toLabel",
            type: "text",
            position: { x: 114, y: 41 },
            width: 80,
            height: 4,
            fontSize: 7.5,
            fontColor: "#94a3b8",
          },
          {
            name: "toAddress",
            type: "text",
            position: { x: 114, y: 47 },
            width: 82,
            height: 18,
            fontSize: 8.5,
            fontColor: "#1e293b",
            lineHeight: 1.3,
          },
          // Inventory table
          {
            ...defaultTableSchema,
            name: "packageItems",
            position: { x: 10, y: 76 },
            width: 190,
            height: 80,
            showHead: true,
            head: ["SKU", "Item Description", "Qty", "Weight", "Location"],
            headWidthPercentages: [20, 45, 10, 10, 15],
            tableStyles: { borderColor: "#cbd5e1", borderWidth: 0.3 },
            headStyles: {
              ...defaultTableSchema.headStyles,
              fontColor: "#ffffff",
              backgroundColor: "#0284c7",
              fontSize: 9,
            },
            bodyStyles: {
              ...defaultTableSchema.bodyStyles,
              fontSize: 8,
              alternateBackgroundColor: "#f0f9ff",
            },
          },
        ],
      ],
    },
    sampleData: [
      {
        headerTitle: "PACKING SLIP & DISPATCH MANIFEST",
        trackingBarcode: "1Z9999999999999999",
        trackingNumberText: "TRACKING: 1Z 999 999 99 9999 9999",
        fromLabel: "SHIP FROM",
        fromAddress: "Colby Logistics Fulfillment Hub\n1200 Maritime Blvd, Dock 8\nOakland, CA 94607",
        toLabel: "SHIP TO",
        toAddress: "Piedmont Research Facility\nAttn: Hardware Receiving Dept\n400 Grand Ave, Suite 200\nPiedmont, CA 94611",
        packageItems: JSON.stringify([
          ["NET-RACK-42U", "42U Server Enclosure Soundproof", "1", "110 lbs", "Aisle 4-B"],
          ["SVR-EPYC-9654", "Dual EPYC 9654 Compute Node 2U", "2", "64 lbs", "Vault 2"],
          ["PWR-UPS-3000VA", "Smart-UPS Online 3000VA Rack", "2", "72 lbs", "Bay 12-A"],
        ]),
      },
    ],
  },

  // 7. VIP Event Pass & Badge
  {
    id: "tmpl_event_pass",
    name: "VIP Event Pass & Conference Badge",
    description: "Compact event ticket or badge with attendee name, VIP pill, event details, and QR verification access.",
    category: "ticket",
    schema: {
      basePdf: { width: 105, height: 148, padding: [6, 6, 6, 6] }, // A6 Portrait Badge
      schemas: [
        [
          {
            name: "eventHeader",
            type: "rectangle",
            position: { x: 6, y: 6 },
            width: 93,
            height: 22,
            color: "#4f46e5",
          },
          {
            name: "eventTitle",
            type: "text",
            position: { x: 8, y: 10 },
            width: 89,
            height: 8,
            fontSize: 12,
            fontColor: "#ffffff",
            alignment: "center",
          },
          {
            name: "eventSub",
            type: "text",
            position: { x: 8, y: 19 },
            width: 89,
            height: 5,
            fontSize: 7,
            fontColor: "#e0e7ff",
            alignment: "center",
          },
          {
            name: "vipPill",
            type: "rectangle",
            position: { x: 34, y: 34 },
            width: 37,
            height: 8,
            color: "#e11d48",
          },
          {
            name: "tierLabel",
            type: "text",
            position: { x: 34, y: 36 },
            width: 37,
            height: 4,
            fontSize: 7.5,
            fontColor: "#ffffff",
            alignment: "center",
          },
          {
            name: "attendeeName",
            type: "text",
            position: { x: 8, y: 48 },
            width: 89,
            height: 10,
            fontSize: 15,
            fontColor: "#0f172a",
            alignment: "center",
          },
          {
            name: "attendeeOrg",
            type: "text",
            position: { x: 8, y: 59 },
            width: 89,
            height: 6,
            fontSize: 8.5,
            fontColor: "#64748b",
            alignment: "center",
          },
          {
            name: "accessQr",
            type: "qrcode",
            position: { x: 32, y: 72 },
            width: 41,
            height: 41,
          },
          {
            name: "passDetails",
            type: "text",
            position: { x: 8, y: 120 },
            width: 89,
            height: 18,
            fontSize: 7.5,
            fontColor: "#334155",
            alignment: "center",
            lineHeight: 1.3,
          },
        ],
      ],
    },
    sampleData: [
      {
        eventTitle: "CLOUD SYMPOSIUM 2026",
        eventSub: "EDGE ARCHITECTURES & AGENTIC SYSTEMS",
        tierLabel: "ALL ACCESS VIP",
        attendeeName: "Justin Bishop",
        attendeeOrg: "Colby Ecosystem / DeepMind AGY",
        accessQr: "https://google-workspace-mcp.hacolby.workers.dev/pass/checkin/VIP-8842",
        passDetails: "Access: Keynote Stage, VIP Lounge & Workshop Labs\nVenue: Moscone Center West, San Francisco\nBadge ID: #CS26-VIP-8842",
      },
    ],
  },
];
