/**
 * @fileoverview Parsers for Google Workspace Events delivered over Cloud Pub/Sub.
 *
 * Pub/Sub push POSTs `{ message: { data: <base64 CloudEvent>, attributes, messageId } }`.
 * Workspace Events may use structured-mode JSON in `data` or binary-mode CloudEvents
 * whose `ce-*` attributes sit on the Pub/Sub message. These helpers decode both
 * shapes, pull the Drive file id, and classify the event family so the E2E health
 * check can map create/rename/comment/delete mutations onto received events.
 *
 * @example
 * ```typescript
 * const { event, messageId, attributes } = decodePubSubPush(body);
 * const resourceId = extractDriveResourceId(event, attributes);
 * ```
 */

/** CloudEvent-shaped Workspace Events payload (loose — Google adds fields). */
export type WorkspaceCloudEvent = {
  id?: string;
  type?: string;
  source?: string;
  subject?: string;
  time?: string;
  data?: unknown;
  [key: string]: unknown;
};

/** Cloud Pub/Sub push envelope posted to this Worker. */
export type PubSubPushEnvelope = {
  message?: {
    data?: string;
    messageId?: string;
    attributes?: Record<string, string>;
  };
  subscription?: string;
};

/** Mutation families the E2E health check exercises. */
export type WorkspaceEventFamily = "create" | "change" | "comment" | "delete" | "other";

/**
 * Decode a Pub/Sub push JSON body into a CloudEvent plus transport metadata.
 *
 * @param body - Parsed JSON from the webhook POST (envelope or a raw CloudEvent)
 * @returns The inner event, Pub/Sub messageId, and CloudEvents attributes
 * @throws Never — malformed bodies yield an empty event object
 */
export function decodePubSubPush(body: unknown): {
  event: WorkspaceCloudEvent;
  messageId?: string;
  attributes?: Record<string, string>;
  subscription?: string;
} {
  if (!body || typeof body !== "object") {
    return { event: {} };
  }
  const envelope = body as PubSubPushEnvelope;
  const message = envelope.message;
  const attributes = message?.attributes;
  const messageId = message?.messageId;
  const subscription = envelope.subscription;

  if (typeof message?.data === "string" && message.data.length > 0) {
    try {
      const decoded = JSON.parse(atob(message.data)) as unknown;
      if (decoded && typeof decoded === "object") {
        return {
          event: decoded as WorkspaceCloudEvent,
          messageId,
          attributes,
          subscription,
        };
      }
    } catch {
      return {
        event: { raw: message.data },
        messageId,
        attributes,
        subscription,
      };
    }
  }

  // Already a CloudEvent (or a probe payload) posted without a Pub/Sub envelope.
  if (!message) {
    return { event: body as WorkspaceCloudEvent };
  }
  return { event: body as WorkspaceCloudEvent, messageId, attributes, subscription };
}

/**
 * Extract the Drive file id from a CloudEvent `subject`, `data.id`, or `ce-subject`.
 *
 * Subjects look like `files/FILE_ID` or `//drive.googleapis.com/files/FILE_ID`.
 *
 * @param event - Decoded CloudEvent
 * @param attributes - Optional Pub/Sub / CloudEvents attributes
 * @returns Bare Drive file id, or null when none is present
 */
export function extractDriveResourceId(
  event: Record<string, unknown>,
  attributes?: Record<string, string>,
): string | null {
  const fromSubject = fileIdFromSubject(asString(event.subject) ?? attributes?.["ce-subject"]);
  if (fromSubject) return fromSubject;

  const data = event.data;
  if (data && typeof data === "object") {
    const rec = data as Record<string, unknown>;
    const nested =
      asString(rec.id) ??
      asString((rec.file as Record<string, unknown> | undefined)?.id) ??
      asString((rec.comment as Record<string, unknown> | undefined)?.file_id) ??
      asString((rec.comment as Record<string, unknown> | undefined)?.fileId) ??
      asString((rec.reply as Record<string, unknown> | undefined)?.file_id) ??
      asString((rec.reply as Record<string, unknown> | undefined)?.fileId);
    if (nested) return nested;
  }
  return asString(event.id) && !asString(event.type) ? asString(event.id) : null;
}

/**
 * Resolve the CloudEvent type from the payload or `ce-type` attribute.
 *
 * @param event - Decoded CloudEvent
 * @param attributes - Optional Pub/Sub / CloudEvents attributes
 * @returns Event type string, or null
 */
export function extractEventType(
  event: Record<string, unknown>,
  attributes?: Record<string, string>,
): string | null {
  return asString(event.type) ?? attributes?.["ce-type"] ?? null;
}

/**
 * Stable id used to dedup Pub/Sub retries in `drive_notifications`.
 *
 * Prefers CloudEvent `id`, then Pub/Sub `messageId`, then a caller-supplied fallback.
 *
 * @param event - Decoded CloudEvent
 * @param messageId - Pub/Sub message id
 * @param fallback - UUID generated by the caller when neither id is present
 * @returns Non-empty notification row id
 */
export function notificationIdFor(
  event: Record<string, unknown>,
  messageId: string | undefined,
  fallback: string,
): string {
  return asString(event.id) ?? messageId ?? fallback;
}

/**
 * Map a Workspace Events CloudEvent type onto the E2E mutation family.
 *
 * @param type - CloudEvent type (e.g. `google.workspace.drive.file.v3.contentChanged`)
 * @returns Family used by the health-check monitor step
 */
export function classifyEventFamily(type: string | null | undefined): WorkspaceEventFamily {
  if (!type) return "other";
  const t = type.toLowerCase();
  if (t.includes("comment")) return "comment";
  if (t.includes("trash") || t.includes("deleted") || t.includes(".delete")) return "delete";
  if (t.includes("created") || t.includes(".create") || t.includes(".added") || t.endsWith(".added")) {
    return "create";
  }
  if (t.includes("contentchanged") || t.includes("updated") || t.includes("moved") || t.includes("renamed")) return "change";
  return "other";
}

/**
 * Pull the last path segment after `files/` (or the last `/` segment) from a subject.
 *
 * @param subject - CloudEvent subject or `ce-subject` attribute
 * @returns Bare id, or null
 */
function fileIdFromSubject(subject: string | null | undefined): string | null {
  if (!subject) return null;
  const filesIdx = subject.lastIndexOf("files/");
  if (filesIdx >= 0) {
    const rest = subject.slice(filesIdx + "files/".length);
    const id = rest.split("/")[0]?.trim();
    return id || null;
  }
  const parts = subject.split("/").filter(Boolean);
  const last = parts[parts.length - 1];
  return last || null;
}

function asString(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}
